jQuery(function($){var BRUSHED=window.BRUSHED||{};var mobileMenuClone=$('#menu').clone().attr('id','navigation-mobile');BRUSHED.mobileNav=function(){var windowWidth=$(window).width();if(windowWidth<=979){if($('#mobile-nav').length>0){mobileMenuClone.insertAfter('#menu');$('#navigation-mobile #menu-nav').attr('id','menu-nav-mobile');}}else{$('#navigation-mobile').css('display','none');if($('#mobile-nav').hasClass('open')){$('#mobile-nav').removeClass('open');}}}
BRUSHED.listenerMenu=function(){$('#mobile-nav').on('click',function(e){$(this).toggleClass('open');if($('#mobile-nav').hasClass('open')){$('#navigation-mobile').slideDown(500,'easeOutExpo');}else{$('#navigation-mobile').slideUp(500,'easeOutExpo');}e.preventDefault();});$('#menu-nav-mobile a').on('click',function(){$('#mobile-nav').removeClass('open');$('#navigation-mobile').slideUp(350,'easeOutExpo');});}
BRUSHED.slider=function(){$.supersized({slideshow:1,autoplay:1,start_slide:0,stop_loop:0,random:0,slide_interval:5000,transition:1,transition_speed:2000,new_window:1,pause_hover:0,keyboard_nav:1,performance:1,image_protect:0,min_width:0,min_height:0,vertical_center:1,horizontal_center:1,fit_always:0,fit_portrait:1,fit_landscape:0,slide_links:'name',thumb_links:1,thumbnail_navigation:1,slides:[{image:'_include/img/work/full/exteriores/exteriores-08.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''},{image:'_include/img/work/full/interiores/interiores-01.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''},{image:'_include/img/work/full/exteriores/exteriores-11.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''},{image:'_include/img/work/full/interiores/interiores-05.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''},{image:'_include/img/work/full/interiores/interiores-03.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''},{image:'_include/img/work/full/interiores/interiores-07.jpg',title:'<div class="slide-content"></div>',thumb:'',url:''}],progress_bar:1,mouse_scrub:1});}
BRUSHED.nav=function(){$('.sticky-nav').waypoint('sticky');$('.pegajoso').waypoint('sticky');}
$(document).on('ready',function(){$(window).scroll(function(){posicionarMenu();})
function posicionarMenu(){var barra=$('.control-nav');var alto_nav=barra.outerHeight();var alto_slide=$('#home-slider').outerHeight();if($(window).scrollTop()>=alto_slide-50){barra.addClass('pegajoso');}else{barra.removeClass('pegajoso');}}});function animarTexto(){var textObjects=[{offset:1000,duration:4000,animation:'fadeIn'},{offset:6000,duration:4000,animation:'fadeIn'},{offset:12000,duration:4000,animation:'fadeIn'},{offset:18000,duration:4000,animation:'fadeIn'},{offset:24000,duration:4000,animation:'fadeIn'},{offset:30000,duration:4000,animation:'fadeIn'}],options={repeat:true},animations={topToBottom:{positions:{start:{top:'50px'},1:{bottom:'50px'}}}};$("#palabras").animateText(textObjects,options,animations);}var $container=$('#projects ul');$container.isotope({});$('#options ul div li a').click(function(){var selector=$(this).attr('data-filter');$container.isotope({filter:selector});return false;});BRUSHED.fancyBox=function(){if($('.fancybox').length>0||$('.fancybox-media').length>0||$('.fancybox-various').length>0){$(".fancybox").fancybox({padding:0,beforeShow:function(){this.title=$(this.element).attr('title');this.title='<h4>'+this.title+'</h4>'+'<p>'+$(this.element).parent().find('img').attr('alt')+'</p>';},helpers:{title:{type:'inside'},}});$('.fancybox-media').fancybox({openEffect:'none',closeEffect:'none',helpers:{media:{}}});}}
BRUSHED.contactForm=function(){$("#contact-submit").on('click',function(){$contact_form=$('#contact-form');var fields=$contact_form.serialize();$.ajax({type:"POST",url:"_include/php/contact.php",data:fields,dataType:'json',success:function(response){if(response.status){$('#contact-form input').val('');$('#contact-form textarea').val('');}$('#response').empty().html(response.html);}});return false;});}
BRUSHED.tweetFeed=function(){var valueTop=-64;$("#ticker").tweet({username:"Bluxart",page:1,avatar_size:0,count:10,template:"{text}{time}",filter:function(t){return!/^@\w+/.test(t.tweet_raw_text);},loading_text:"loading ..."}).bind("loaded",function(){var ul=$(this).find(".tweet_list");var ticker=function(){setTimeout(function(){ul.find('li:first').animate({marginTop:valueTop+'px'},500,'linear',function(){$(this).detach().appendTo(ul).removeAttr('style');});ticker();},5000);};ticker();});}
BRUSHED.menu=function(){$('#menu-nav, #menu-nav-mobile').onePageNav({currentClass:'current',changeHash:false,scrollSpeed:750,scrollOffset:30,scrollThreshold:0.5,easing:'easeOutExpo',filter:':not(.external)'});}
BRUSHED.goSection=function(){$('#nextsection').on('click',function(){$target=$($(this).attr('href')).offset().top-30;$('body, html').animate({scrollTop:$target},750,'easeOutExpo');return false;});}
BRUSHED.goUp=function(){$('#goUp').on('click',function(){$target=$($(this).attr('href')).offset().top-30;$('body, html').animate({scrollTop:$target},750,'swing');return false;});}
BRUSHED.irAlContacto=function(){$('.ir-al-contacto').on('click',function(){$target=$($(this).attr('href')).offset().top-30;$('body, html').animate({scrollTop:$target},750,'swing');return false;});}
BRUSHED.scrollToTop=function(){var windowWidth=$(window).width(),didScroll=false;var $arrow=$('#back-to-top');var $logo=$('#ir-al-inicio');$arrow.click(function(e){$('body,html').animate({scrollTop:"0"},2000,'swing');e.preventDefault();})
$logo.click(function(){$('body,html').animate({scrollTop:"0"},2000,'swing');})
$(window).scroll(function(){didScroll=true;});setInterval(function(){if(didScroll){didScroll=false;if($(window).scrollTop()>1000){$arrow.css('display','block');}else{$arrow.css('display','none');}}},250);}
BRUSHED.utils=function(){$('.item-thumbs').bind('touchstart',function(){$(".active").removeClass("active");$(this).addClass('active');});$('.image-wrap').bind('touchstart',function(){$(".active").removeClass("active");$(this).addClass('active');});$('#social ul li').bind('touchstart',function(){$(".active").removeClass("active");$(this).addClass('active');});}
BRUSHED.accordion=function(){var accordion_trigger=$('.accordion-heading.accordionize');accordion_trigger.delegate('.accordion-toggle','click',function(event){if($(this).hasClass('active')){$(this).removeClass('active');$(this).addClass('inactive');}else{accordion_trigger.find('.active').addClass('inactive');accordion_trigger.find('.active').removeClass('active');$(this).removeClass('inactive');$(this).addClass('active');}event.preventDefault();});}
BRUSHED.toggle=function(){var accordion_trigger_toggle=$('.accordion-heading.togglize');accordion_trigger_toggle.delegate('.accordion-toggle','click',function(event){if($(this).hasClass('active')){$(this).removeClass('active');$(this).addClass('inactive');}else{$(this).removeClass('inactive');$(this).addClass('active');}event.preventDefault();});}
BRUSHED.toolTip=function(){$('a[data-toggle=tooltip]').tooltip();}
BRUSHED.slider();$(document).ready(function(){function EmularClick(){$('#options ul div li a#clickInicio').click();}setTimeout(EmularClick,4000);Modernizr.load([{test:Modernizr.placeholder,nope:'_include/js/placeholder.js',complete:function(){if(!Modernizr.placeholder){Placeholders.init({live:true,hideOnFocus:false,className:"yourClass",textColor:"#999"});}}}]);BRUSHED.nav();BRUSHED.mobileNav();BRUSHED.listenerMenu();BRUSHED.menu();BRUSHED.goSection();BRUSHED.goUp();BRUSHED.irAlContacto();BRUSHED.fancyBox();BRUSHED.contactForm();BRUSHED.tweetFeed();BRUSHED.scrollToTop();BRUSHED.utils();BRUSHED.accordion();BRUSHED.toggle();BRUSHED.toolTip();});$(window).resize(function(){BRUSHED.mobileNav();});});